In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

read the data frame

In [3]:
df = pd.read_csv(r"C:\Users\oussama\Desktop\PFF\raw data\1699460825-wide_2023_sept (2).csv")
df

C:\Users\oussama\AppData\Local\Temp\ipykernel_14232\3878698096.py:1: DtypeWarning: Columns (0: level, 1: region, 2: ethnicity, 3: religion, 4: language, 5: disability, 6: hh_edu_head) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\oussama\Desktop\PFF\raw data\1699460825-wide_2023_sept (2).csv")

,Unnamed: 0,iso_code,region_group,income_group,country,survey,year,level,grade,category,...,rlevel3_m,rlevel3_no,slevel3_m,slevel3_no,mlevel4_m,mlevel4_no,rlevel4_m,rlevel4_no,slevel4_m,slevel4_no
0,58194,GIN,Sub-Saharan Africa,Lower middle income,Guinea,Census,1996,NaN,1,Total,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,58434,GIN,Sub-Saharan Africa,Lower middle income,Guinea,Census,1996,NaN,1,Sex,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,58676,GIN,Sub-Saharan Africa,Lower middle income,Guinea,Census,1996,NaN,1,Sex,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62010,GIN,Sub-Saharan Africa,Lower middle income,Guinea,Census,1996,NaN,1,Location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62235,GIN,Sub-Saharan Africa,Lower middle income,Guinea,Census,1996,NaN,1,Location & Sex,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215573,143316,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,NaN,1,Location & Sex,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215574,143317,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,NaN,1,Location & Sex,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215575,143318,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,NaN,1,Sex,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215576,143319,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,NaN,1,Sex,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215577,143320,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,NaN,1,Total,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Top 5 rows

In [ ]:
df.head()

Variables data types

In [ ]:
df.info()

trins1 : limite the datset between 2000 and 2022

In [ ]:
df = df[(df['year'] >= 2000)]

In [ ]:
iso_code = [df['iso_code'].unique()]

looking for duplicate rows

In [ ]:
#looking for duplicate rows
df.duplicated().sum()

Messing Values detect

In [ ]:
df.isnull().sum()

delete culomns
#cause : no need, had no effect on data moduling, too messing values,

In [ ]:
df.drop(columns=['Unnamed: 0',
                        'level',
                        'grade',
                        'ethnicity',
                        'religion',
                        'disability',
                        'hh_edu_head', 
                        'disability', 
                        'disability', 
                        'disability', 
                        'preschool_3_m', 
                        'preschool_3_no', 
                        'preschool_1ybefore_m', 
                        'preschool_1ybefore_no'],inplace = True)

In [ ]:
df['survey'].value_counts()

In [ ]:
# Keep only countries that have MORE than 100 rows of data
df = df[df.groupby('iso_code')['iso_code'].transform('count') > 100]

In [ ]:
df

In [ ]:
# Analyze outliers within specific segments rather than globally
df_low_income = df[df['income_group'] == 'Low income']
df_low_mid_income = df[df['income_group'] =='Lower middle income' ]
df_upper_mid_income = df[df['income_group'] =='Upper middle income']
df_high_income = df[df['income_group'] =='Hirgh income']

In [ ]:
df_low_income

In [ ]:
MAR_educ = df[df['iso_code'] == 'MAR']

In [ ]:
MAR_educ
MAR_educ.to_csv("MIDE.csv")

In [ ]:
MAR_educ.isnull().sum()

In [ ]:
df.to_csv("WIDE_clean.csv")
df_low_income.to_csv("low_income.csv")
df_low_mid_income.to_csv("low_mid_income.csv")
df_upper_mid_income.to_csv("upper_mid_income.csv")
df_high_income.to_csv("high_income.csv")

In [4]:
df = pd.read_csv(r"C:\Users\oussama\Desktop\PFF\generated_data\WIDE_clean.csv")
df

,iso_code,region_group,income_group,country,survey,year,category,sex,location,wealth,...,rlevel3_m,rlevel3_no,slevel3_m,slevel3_no,mlevel4_m,mlevel4_no,rlevel4_m,rlevel4_no,slevel4_m,slevel4_no
0,ALB,Europe and Northern America,Upper middle income,Albania,MICS,2000,Location,NaN,Rural,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALB,Europe and Northern America,Upper middle income,Albania,MICS,2000,Location,NaN,Urban,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ALB,Europe and Northern America,Upper middle income,Albania,MICS,2000,Location & Sex,Female,Rural,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALB,Europe and Northern America,Upper middle income,Albania,MICS,2000,Location & Sex,Female,Urban,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALB,Europe and Northern America,Upper middle income,Albania,MICS,2000,Location & Sex,Male,Rural,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214977,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,Location & Sex,Male,Rural,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214978,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,Location & Sex,Male,Urban,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214979,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,Sex,Female,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214980,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,Sex,Male,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214981,BFA,Sub-Saharan Africa,Low income,Burkina Faso,HFPS,2022,Total,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN